### ISSUE TITLE
Empty device enumeration should not return NULL

### ISSUE THREAD

**Issue by helluvamatt** [nvchernov/hidapiadapter#1]
`HidDeviceManager.SearchDevices()` should return an empty list when there are no devices that match the criteria, rather than `NULL`.

For example:

```C#
var devices = HidDeviceManager.GetManager().SearchDevices(0xFEED, 0xDAD1).Select(d => d.ToString());
foreach (var dev in devices) Console.WriteLine(dev);
```

This throws an exception (`System.ArgumentNullException: 'Value cannot be null. Parameter name: source'`) when the enumeration is empty (ie. no devices matched the query).

This could be solved at HidApiAdapter/HidDeviceManager.cs#L60 by changing `null` to `devices`.

**Comment by helluvamatt** [comment]
As a workaround, the above code could be written as:

```C#
var devices = (HidDeviceManager.GetManager().SearchDevices(0xFEED, 0xDAD1) ?? new List<HidDevice>()).Select(d => d.ToString());
foreach (var dev in devices) Console.WriteLine(dev);
```

**Comment by nvchernov** [comment]
ok, thanks, it's really better to return empty array instead of null
