### ISSUE TITLE
hidapi32 not found?

### ISSUE THREAD

**Issue by Mek7** [nvchernov/hidapiadapter#6]
Hi,
I just migrated to windows 11 from windows 10 and my program that uses your library fails to initialize.

`System.TypeInitializationException: 'The type initializer for 'HidApiAdapter.HidDeviceManager' threw an exception.'
DllNotFoundException: Unable to load DLL 'hidapi32': The specified module could not be found. (Exception from HRESULT: 0x8007007E)`

on this call:

`var devices = HidDeviceManager.GetManager().SearchDevices(0x16C0, 0x05DF);`
But both hidapi32 and hidapi64.dll are set as Content and Copy if newer, and they exist in the bin directory.
What is wrong?

**Comment by nvchernov** [comment]
@Mek7 Hi, i need to find windows 11 somewhere and try to replay it. 
When i get to this problem i will look at it.

Thanks!

**Comment by Mek7** [comment]
Well, after I continued with installation of other software, like VS2022, printer drivers, etc... somehow it started working again. I suppose there must have been some C++ Redistributable package missing or something like that...

**Comment by nvchernov** [comment]
Great, thanks, i will update docs. Yep, it's true that you need to install C++ Redistributable package

**Comment by Mek7** [comment]
Yes, you need to install the redist, but which one? There are so many versions of it...
